seed: 2022
debug: False
enable_amp_half_precision: False
epochs: 10
epochs_debug: 5
img_size: 224
model_name: efficientnet_b0
embedding_size: 512
train_batch_size: 32
train_batch_size_debug: 32
valid_batch_size: 64
valid_batch_size_debug: 64
learning_rate: 0.0001
scheduler: CosineAnnealingLR
min_lr: 1.0e-06
T_max: 500
T_0: 500
weight_decay: 1.0e-06
n_fold: 5
n_accumulate: 1