seed: 2022
epochs: 6
img_size: 224
model_name: efficientnet_b0
embedding_size: 512
train_batch_size: 32
valid_batch_size: 64
learning_rate: 0.0001
scheduler: CosineAnnealingLR
min_lr: 1.0e-06
T_max: 500
weight_decay: 1.0e-06
n_fold: 5
n_accumulate: 1
# ArcFace Hyperparameters
s: 30.0
m: 0.5
ls_eps: 0.0
easy_margin: false