version: '3'

services:
  application:
    restart: always
    build:
      context: ./customed_python3_10
      dockerfile: Dockerfile
    image: my_python # specify name image
    container_name: app3
    tty: true
    working_dir: /usr/local/mount_dir
    environment:
      TZ: Asia/Tokyo
    volumes:
      - type: bind
        source: ./
        target: /usr/local/mount_dir
