wandb_version: 1

T_0:
  desc: null
  value: 500
T_max:
  desc: null
  value: 500
_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.8
    start_time: 1667290338.607406
    t:
      1:
      - 1
      - 5
      - 41
      - 49
      - 53
      - 55
      - 63
      - 80
      2:
      - 1
      - 5
      - 41
      - 49
      - 53
      - 55
      - 63
      - 80
      3:
      - 1
      - 16
      - 23
      4: 3.10.8
      5: 0.13.4
      8:
      - 5
debug:
  desc: null
  value: true
device:
  desc: null
  value: cpu
embedding_size:
  desc: null
  value: 512
enable_amp_half_precision:
  desc: null
  value: false
epochs:
  desc: null
  value: 8
epochs_debug:
  desc: null
  value: 20
img_size:
  desc: null
  value: 224
learning_rate:
  desc: null
  value: 0.0001
min_lr:
  desc: null
  value: 1.0e-06
model_name:
  desc: null
  value: efficientnet_b0
n_accumulate:
  desc: null
  value: 1
n_fold:
  desc: null
  value: 5
num_classees:
  desc: null
  value: 10
out_features:
  desc: null
  value: 10
scheduler:
  desc: null
  value: CosineAnnealingLR
seed:
  desc: null
  value: 2022
train_batch_size:
  desc: null
  value: 32
train_batch_size_debug:
  desc: null
  value: 32
valid_batch_size:
  desc: null
  value: 64
valid_batch_size_debug:
  desc: null
  value: 64
weight_decay:
  desc: null
  value: 1.0e-06
